# Python dependencies required to generate documentation
# pip install mkdocs mkdocs-material mkdocs-material-extensions mkdocs-with-pdf 

site_name: Xpra
site_url: https://xpra.org/wiki/
site_description: >-
  Manage your remote systems with first-class virtual desktop support and connect
  in seconds – sound, printing, notifications wherever you work

repo_name: xpra-org/xpra
repo_url: https://github.com/xpra-org/xpra

copyright: Xpra Authors
site_author: Xpra.org

docs_dir: docs

theme:
  name: material
  custom_dir: docs/.overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: http://xpra.org/icons/xpra-logo.png
  logo: http://xpra.org/icons/xpra-logo.png

plugins: 
  - search
  # - with-pdf:
  #     author: Xpra Authors
  #     copyright: 2023 Xpra Authors
  #     cover_title: Xpra Documentation
  #     output_path: docs.pdf

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - smarty
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: xpra-org
      repo: xpra
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting started:
    - Installation:
      - Installation.md
      - Supported Operating Systems: Platforms.md
    - Bug reporting:
      - Report a Bug: Debugging.md
    - Examples: Usage-Examples.md
    - Versions: Versions.md
  - Starting: 
    - Start Desktop: Usage/Start-Desktop.md
    - Start Shadow: Usage/Shadow-Server.md
    - Seamless: Usage/Seamless.md
  - Setup:
    - Audio: Features/Audio.md
    - Video: Features/Image-Depth.md
    - Clipboard: Features/Clipboard.md
    - Display: Features/Display.md
    - DPI: Features/DPI.md
    - File Transfer: Features/File-Transfers.md
    - Keyboard: Features/Keyboard.md
    - Notifications: Features/Notifications.md
    - Remote Printing: Features/Printing.md
    - System Tray: Features/System-Tray.md
    - Webcam: Features/Webcam.md
    - Configure Network: 
      - Network/README.md
      - AES: Network/AES.md
      - Encryption: Network/Encryption.md
      - Multicast DNS: Network/Multicast-DNS.md
      - SSH: Network/SSH.md
      - SSL: Network/SSL.md
    - Advanced:
      - Usage/README.md
      - Authentication: Usage/Authentication.md
      - Client OpenGL: Usage/Client-OpenGL.md
      - Client: Usage/Client.md
      - Configuration: Usage/Configuration.md
      - Encodings: 
        - Introduction: Usage/Encodings.md
        - Nvidia: Usage/NVENC.md
      - Logging: Usage/Logging.md
      - OpenGL: Usage/OpenGL.md
      - Security: Usage/Security.md
      - XDummy: Usage/Xdummy.md
      - Use with Apache: Usage/Apache-Proxy.md
      - Use in WSL: Usage/WSL.md
      - Use Behind a Proxy: Usage/Proxy-Server.md
  - Changelog: CHANGELOG.md
